USE [master]
GO
CREATE DATABASE [Lab4Rivers]
GO
USE [Lab4Rivers]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rivers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [ntext] NOT NULL,
	[Lenght] [int] NOT NULL,
	[FallsIn] [ntext] NOT NULL,
	[AnnualRunoff] [int] NOT NULL,
	[CoolArea] [int] NOT NULL,
 CONSTRAINT [PK_Rivers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [Lab4Rivers] SET  READ_WRITE 
GO